#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1E8ABDC773EDE252 (timograham@gmail.com)
#
Name     : Django
Version  : 1.11
Release  : 51
URL      : http://pypi.debian.net/Django/Django-1.11.tar.gz
Source0  : http://pypi.debian.net/Django/Django-1.11.tar.gz
Source99 : http://pypi.debian.net/Django/Django-1.11.tar.gz.asc
Summary  : A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT Python-2.0
Requires: Django-bin
Requires: Django-python
Requires: bcrypt
Requires: pytz
BuildRequires : Django
BuildRequires : Jinja2-python
BuildRequires : MarkupSafe
BuildRequires : MarkupSafe-python
BuildRequires : Pillow
BuildRequires : PyYAML
BuildRequires : bcrypt
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : docutils
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-memcached
BuildRequires : python-mock
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : pytz
BuildRequires : selenium
BuildRequires : setuptools
BuildRequires : six
BuildRequires : sqlparse
BuildRequires : tzdata

%description
The documentation in this tree is in plain text files and can be viewed using
any text file viewer.

%package bin
Summary: bin components for the Django package.
Group: Binaries

%description bin
bin components for the Django package.


%package python
Summary: python components for the Django package.
Group: Default
Provides: django-python

%description python
python components for the Django package.


%prep
%setup -q -n Django-1.11

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492013880
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd tests ; PYTHONPATH=..: ./runtests.py -v 2 || : ; popd
%install
export SOURCE_DATE_EPOCH=1492013880
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/django-admin
/usr/bin/django-admin.py

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
